server:
  port: 8080



security:
  cors:
    urls: "http://localhost:3000"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_registry
    username: user
    password: "PersonReg123!"
    driver-class-name: com.mysql.cj.jdbc.Driver




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


integration-service:
  config:
    country: ${INTEGRATION_COUNTRY:IT}
  stacktrace-exception:
    enabled: true


logging:
  config: classpath:log4j2.yaml


