server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${REGISTRY_KEYSTORE_PATH}
    key-store-password: ${REGISTRY_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: registry

security:
  cors:
    urls: ${SECURITY_CORS_URLS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

integration-service:
  stacktrace-exception:
    enabled: true




